theme: jekyll-theme-dinky
title: Isabel's Project Home Page
description: This is where I post short write-ups explaining the projects I'm working on.
<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
